export const MatchEventErrorCodes = {
  NOT_FOUND: 'MATCH_EVENT_NOT_FOUND',
  MATCH_NOT_LIVE: 'MATCH_EVENT_MATCH_NOT_LIVE',
  PLAYER_NOT_IN_MATCH: 'MATCH_EVENT_PLAYER_NOT_IN_MATCH',
  PLAYER_ALREADY_EJECTED: 'MATCH_EVENT_PLAYER_ALREADY_EJECTED',
  WRONG_MATCH: 'MATCH_EVENT_WRONG_MATCH',
} as const
