export const OnboardingErrorCodes = {
  ONBOARDING_ALREADY_COMPLETE: 'ONBOARDING_CONFLICT_ALREADY_COMPLETE',
  USERNAME_TAKEN: 'ONBOARDING_CONFLICT_USERNAME_TAKEN',
  SLUG_TAKEN: 'ONBOARDING_CONFLICT_SLUG_TAKEN',
} as const
