version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: 4sports-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: 4sports
      POSTGRES_PASSWORD: 4sports_pass
      POSTGRES_DB: 4sports_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
