export const TournamentErrorCodes = {
  NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  NOT_DRAFT: 'TOURNAMENT_NOT_DRAFT',
  LIMIT_EXCEEDED: 'TOURNAMENT_LIMIT_EXCEEDED',
  FORMAT_NOT_AVAILABLE: 'FORMAT_NOT_AVAILABLE_ON_PLAN',
  PUBLISH_VALIDATION: 'TOURNAMENT_PUBLISH_VALIDATION',
  FORBIDDEN: 'TOURNAMENT_FORBIDDEN',
} as const
