export const TeamErrorCodes = {
  NOT_FOUND: 'TEAM_NOT_FOUND',
  FORBIDDEN: 'TEAM_FORBIDDEN',
  MEMBER_NOT_FOUND: 'TEAM_MEMBER_NOT_FOUND',
  LAST_CAPTAIN: 'TEAM_LAST_CAPTAIN',
  ALREADY_INVITED: 'TEAM_ALREADY_INVITED',
  ALREADY_MEMBER: 'TEAM_ALREADY_MEMBER',
} as const
