export const RegistrationErrorCodes = {
  NOT_FOUND: 'REGISTRATION_NOT_FOUND',
  TOURNAMENT_NOT_FOUND: 'REGISTRATION_TOURNAMENT_NOT_FOUND',
  TOURNAMENT_NOT_OPEN: 'REGISTRATION_TOURNAMENT_NOT_OPEN',
  TEAM_NOT_FOUND: 'REGISTRATION_TEAM_NOT_FOUND',
  NOT_CAPTAIN: 'REGISTRATION_NOT_CAPTAIN',
  ALREADY_REGISTERED: 'REGISTRATION_ALREADY_REGISTERED',
  TOURNAMENT_FULL: 'REGISTRATION_TOURNAMENT_FULL',
  ELIGIBILITY_BLOCKED: 'REGISTRATION_ELIGIBILITY_BLOCKED',
  FORBIDDEN: 'REGISTRATION_FORBIDDEN',
  INVALID_TRANSITION: 'REGISTRATION_INVALID_TRANSITION',
} as const
