export const DisputeErrorCodes = {
  NOT_FOUND: 'DISPUTE_NOT_FOUND',
  MATCH_NOT_FOUND: 'DISPUTE_MATCH_NOT_FOUND',
  MATCH_NOT_FINISHED: 'DISPUTE_MATCH_NOT_FINISHED',
  WINDOW_EXPIRED: 'DISPUTE_WINDOW_EXPIRED',
  ALREADY_OPEN: 'DISPUTE_ALREADY_OPEN',
  NOT_OPEN: 'DISPUTE_NOT_OPEN',
} as const
