export const ConvocatoriaErrorCodes = {
  NOT_FOUND: 'CONVOCATORIA_NOT_FOUND',
  MATCH_NOT_FOUND: 'CONVOCATORIA_MATCH_NOT_FOUND',
  INVALID_TEAM: 'CONVOCATORIA_INVALID_TEAM',
  MATCH_ALREADY_ENDED: 'CONVOCATORIA_MATCH_ALREADY_ENDED',
  NOT_YOUR_CONVOCATORIA: 'CONVOCATORIA_NOT_YOUR_CONVOCATORIA',
} as const
