export const PlayerClaimErrorCodes = {
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  CLAIM_NOT_ALLOWED: 'CLAIM_NOT_ALLOWED',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  CLAIM_NOT_FOUND: 'CLAIM_NOT_FOUND',
  ALREADY_CLAIMED: 'ALREADY_CLAIMED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
} as const
