// Central registry of fixed UUIDs for dummy data.
//
// Every dummy seed file references these constants so that re-running the seed
// is deterministic and idempotent (insert + onConflictDoNothing on the PK).
// BetterAuth users are NOT here — their IDs are generated by the library and are
// threaded through the seed functions via the `userIds` map keyed by email.
//
// Scheme: 0000XXXX-0000-4000-8000-0000000000NN where XXXX groups by entity.

export const ORG_IDS = {
  ligaMonterrey: '00000001-0000-4000-8000-000000000001',
} as const

export const VENUE_IDS = {
  estadioNorte: '00000002-0000-4000-8000-000000000001',
  canchaSur: '00000002-0000-4000-8000-000000000002',
} as const

export const TOURNAMENT_IDS = {
  ligaApertura: '00000003-0000-4000-8000-000000000001',
  copaRelampago: '00000003-0000-4000-8000-000000000002',
  borrador: '00000003-0000-4000-8000-000000000003',
} as const

export const TEAM_IDS = {
  tigres: '00000004-0000-4000-8000-000000000001',
  rayados: '00000004-0000-4000-8000-000000000002',
  pumas: '00000004-0000-4000-8000-000000000003',
  aguilas: '00000004-0000-4000-8000-000000000004',
} as const

// 4 players per team. Key = `${teamKey}${n}`.
export const PLAYER_IDS = {
  tigres1: '00000005-0000-4000-8000-000000000011',
  tigres2: '00000005-0000-4000-8000-000000000012',
  tigres3: '00000005-0000-4000-8000-000000000013',
  tigres4: '00000005-0000-4000-8000-000000000014',
  rayados1: '00000005-0000-4000-8000-000000000021',
  rayados2: '00000005-0000-4000-8000-000000000022',
  rayados3: '00000005-0000-4000-8000-000000000023',
  rayados4: '00000005-0000-4000-8000-000000000024',
  pumas1: '00000005-0000-4000-8000-000000000031',
  pumas2: '00000005-0000-4000-8000-000000000032',
  pumas3: '00000005-0000-4000-8000-000000000033',
  pumas4: '00000005-0000-4000-8000-000000000034',
  aguilas1: '00000005-0000-4000-8000-000000000041',
  aguilas2: '00000005-0000-4000-8000-000000000042',
  aguilas3: '00000005-0000-4000-8000-000000000043',
  aguilas4: '00000005-0000-4000-8000-000000000044',
} as const

export const EVENT_TYPE_IDS = {
  gol: '00000006-0000-4000-8000-000000000001',
  amarilla: '00000006-0000-4000-8000-000000000002',
  roja: '00000006-0000-4000-8000-000000000003',
} as const

export const MATCH_IDS = {
  // Round-robin among the 4 teams in Liga Apertura.
  // Finished:
  tigresVsRayados: '00000007-0000-4000-8000-000000000001',
  pumasVsAguilas: '00000007-0000-4000-8000-000000000002',
  tigresVsPumas: '00000007-0000-4000-8000-000000000003',
  // Scheduled (future):
  rayadosVsAguilas: '00000007-0000-4000-8000-000000000004',
  tigresVsAguilas: '00000007-0000-4000-8000-000000000005',
  rayadosVsPumas: '00000007-0000-4000-8000-000000000006',
} as const

export const STANDING_IDS = {
  ligaApertura: '00000008-0000-4000-8000-000000000001',
} as const
