export const OrgErrorCodes = {
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_MEMBER_NOT_FOUND: 'ORG_MEMBER_NOT_FOUND',
  ORG_INSUFFICIENT_ROLE: 'ORG_FORBIDDEN_INSUFFICIENT_ROLE',
  ORG_PROFILE_NOT_FOUND: 'ORG_NOT_FOUND_PROFILE',
  ORG_SLUG_CONFLICT: 'ORG_CONFLICT_SLUG_TAKEN',
  ORG_PLAN_NOT_FOUND: 'ORG_NOT_FOUND_PLAN',
  ORG_INVITATION_NOT_FOUND: 'ORG_NOT_FOUND_INVITATION',
  ORG_INVITATION_EXPIRED: 'ORG_CONFLICT_INVITATION_EXPIRED',
  ORG_ALREADY_OWNER: 'ORG_CONFLICT_ALREADY_OWNER',
} as const
