export const OrgErrorCodes = {
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_MEMBER_NOT_FOUND: 'ORG_MEMBER_NOT_FOUND',
  ORG_INSUFFICIENT_ROLE: 'ORG_FORBIDDEN_INSUFFICIENT_ROLE',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_FORBIDDEN: 'INVITATION_FORBIDDEN',
  INVITATION_ALREADY_PROCESSED: 'INVITATION_ALREADY_PROCESSED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
} as const
