export const MatchErrorCodes = {
  NOT_FOUND: 'MATCH_NOT_FOUND',
  FORBIDDEN: 'MATCH_FORBIDDEN',
  NOT_EDITABLE: 'MATCH_NOT_EDITABLE',
  INVALID_STATUS_TRANSITION: 'MATCH_INVALID_STATUS_TRANSITION',
  NOT_LIVE: 'MATCH_NOT_LIVE',
  ALREADY_FINISHED: 'MATCH_ALREADY_FINISHED',
  INVALID_TEAMS: 'MATCH_INVALID_TEAMS',
} as const
